### ISSUE TITLE
Keep last state of blinds after power loss

### ISSUE THREAD

**Issue by rsporny** [rsporny/homebridge-gpio-blinds#12]

**Comment by adobe75** [comment]
Can we write this.currentPosition to log file (on disk?) without big performance hit? And then read this back in on plugin init?

**Comment by rsporny** [comment]
We are gonna use local storage with this lib https://www.npmjs.com/package/node-persist. It's much faster than writing to a file.

**Comment by rsporny** [comment]
resolved in release v1.1.2
