### ISSUE TITLE
Extend GPIO PINs via MCP23017

### ISSUE THREAD

**Issue by niniob** [rsporny/homebridge-gpio-blinds#28]
Hi, 

many thanks for this great homebridge plugin. Works as expected, especially the support for external switches is really cool. 

So far, I have two blinds configured, but in total I have 10 blinds and I'm wondering how to get the additional GPIOs. 10 blinds means 20 relays (=> 20 PINs) and 20 switches (10 for up, 10 for down => 20 PINs). So, in total I need 40 PINs. Therefore I'm trying to use a MCP23017 based GPIO expander (https://www.abelectronics.co.uk/p/54/io-pi-plus). In general the GPIO expander seems to work (e.g. via https://github.com/pandaunit/homebridge-io-switch), but how can I use the additional GPIOs in homebridge-gpio-blinds? Can I just use '27', '28' etc. as additional PIN numbers? But where to configure the I2C address (e.g. 0x21). 

Thanks in advanced for your support.

**Comment by rsporny** [comment]
Hi @niniob,

I'm glad it works for you.

I'm afraid my knowledge about I2C is not good enough to give people advices. Please, search for tutorial on the internet. I hope you find answers.

Good luck.
