### ISSUE TITLE
Relay management

### ISSUE THREAD

**Issue by kiondi** [rsporny/homebridge-gpio-blinds#3]
Hello
The plugin works fine with homebridge.
How can I do to reverse the GPIO exit when it work?
The plugin set the port **HIGH**as default, when the blind stop, and **LOW** when the blind work. 
Thanks

**Comment by kiondi** [comment]
I need trigger the relay by the HIGH level

**Comment by rsporny** [comment]
Hi, sure I will make the active gpio configurable in a couple of days.

**Comment by hyperbart** [comment]
Might be related to my issue to. Afaik we need a HIGH to start the blinds.

**Comment by hyperbart** [comment]
I saw you pushed, will look through code later on, super work, thanks!

Just out of curiosity: do you mind sharing which motor you have for your blinds and how you have wired them to your relay board (NO/NC?). Because both @martijndierckx and I were pretty surprised to see that you need an inverted open to control your motor?

**Comment by rsporny** [comment]
@hyperbart I've got relay module as in README [here](https://botland.com.pl/przekazniki/6941-szesnastokanalowy-modul-przekaznikow-rm13-12v-z-izolacja-optoelektroniczna-10a125vac.html?search_query=MOD-06941&results=1). All the wires from the roller blinds goes directly to garage where this whole setup is connected with raspberry. I don't have any switches near windows, all of this is controlled via iOS Home app only.

![img_44592](https://user-images.githubusercontent.com/5943325/33034306-b2f0159a-ce27-11e7-82c5-2ec73895f8bb.JPG)

**Comment by rsporny** [comment]
@kiondi sorry for taking it so long. Fixed in [v1.0.1](https://github.com/rsporny/homebridge-gpio-blinds/tree/v1.0.1).

**Comment by hyperbart** [comment]
Works perfect!

You're gonna laugh a little bit but I found a new "enhancement" 😄 .

A dual-controlled blind (a blind with a fixed switch and the homebridge-gpio-blinds) does not report back a state, so you could get a mismatched object in HomeKit where it thinks it is closed or open while it's the opposite. The guys at homebridge-rasppi-gpio-garagedoor have solved this by including a reed-switch/magnet-switch which signals is the garagedoor is open or closed.
